---

- name: Install main PHP version
  yum:
    name: "php{{ php_ver }}w"
    state: installed
  loop: "{{ php_modules }}"

- name: Install PHP modules
  yum:
    name: "php{{ php_ver }}w-{{ item }}"
    state: installed
  loop: "{{ php_modules }}"
