---

- name: Configure php-fpm
  template:
    src: "php-fpm.conf.j2"
    dest: "{{ php_fpm_directory }}/{{ item.domain }}.conf"
    mode: 0644
  loop: "{{ websites }}"
  notify: Restart php-fpm
  when: php_fpm_enabled|bool

- name: Enable php-fpm
  service:
    name: php-fpm
    enabled: yes
  notify: Restart php-fpm
  when: php_fpm_enabled|bool
